### ISSUE TITLE
Where is the Java2D viewer?

### ISSUE THREAD

**Issue by fernandospr** [miffels/org.obj2openjl#1]
In the README.MD, you mention a project `org.obj2openjl.ui` that contains a simple Java2D viewer, however I cannot find it.

Please, can you add it?

**Comment by fernandospr** [comment]
I found it: https://github.com/miffels/org.obj2openjl.ui

Maybe you could add a link to it in the README.md.

Thanks.

**Comment by miffels** [comment]
Hi @fernandospr,

Sorry for the late response, I just saw your message since my email provider apparently started treating Github mails as spam. I'll add a link to the README.

Best,
Michael
